import type { Metadata } from "next";
import "./globals.css";
import Cursor from "@/components/cursor";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Cursor/>
        {children}
      </body>
    </html>
  );
}
